# Define glob expressions to use (only valid at root)
globs:
  - "**/*.md"

# Disable rules for specific files or directories
ignores:
  - "node_modules/**"
  - "packages/**/dist/**"
  - "**/*.pcf"
  - GEMINI.md

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

fix: true

config:
  MD033:
    allowed_elements: ["p", "a", "img"]
  MD013: false

