openapi: 3.1.0
info:
  title: Lead Schema
  version: 1.0.0
paths: {}
components:
  schemas:
    Lead:
      type: object
      properties:
        first_name:
          type: string
          nullable: true
        last_name:
          type: string
          nullable: true
        email:
          type: string
          format: email
        phone_number:
          type: string
          nullable: true
        company:
          type: string
          nullable: true
          maxLength: 128
        title:
          type: string
          nullable: true
          maxLength: 128
        product_interest:
          type: string
          enum: ['cat', 'dog', 'cat+dog']
          nullable: true
        notes:
          type: string
          nullable: true
          maxLength: 5000
        customer_facing_notes:
          type: string
          nullable: true
      required:
        - email
